name: Run Smoke Tests

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Test scenario tags"
        required: true
        default: "smoke"

jobs:
  run_smoke_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          cd tests/
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          cd tests/
          python -m pytest -v --gherkin-terminal-reporter -s --tags="${{ github.event.inputs.tags }}"
